### ISSUE TITLE
Error: Invalid assembly manifest

### ISSUE THREAD

**Issue by jonatan-cepsa** [aws-samples/amazon-mwaa-examples#62]
Hello, 
when trying to deploy I get the following error.
I have configured the .env file as you indicate and I have also tried with export but it still gives me the same error
> 
```shell
Error: Invalid assembly manifest:
instance.missing[0].props.account is not of a type(s) string
instance.missing[0].props requires property "filters"
instance.missing[0].props.account is not of a type(s) string
instance.missing[0].props.account is not of a type(s) string
instance.missing[0].props requires property "domainName"
instance.missing[0].props.account is not of a type(s) string
instance.missing[0].props requires property "parameterName"
instance.missing[0].props.account is not of a type(s) string
instance.missing[0].props.account is not of a type(s) string
instance.missing[0].props requires property "serviceName"
instance.missing[0].props.account is not of a type(s) string
instance.missing[0].props requires property "loadBalancerType"
instance.missing[0].props.account is not of a type(s) string
instance.missing[0].props requires property "loadBalancerType"
instance.missing[0].props.account is not of a type(s) string
instance.missing[0].props.account is not of a type(s) string
instance.missing[0].props requires property "aliasName"
instance.missing[0].props requires property "pluginName"
instance.missing[0].props is not any of <#/definitions/AmiContextQuery>,<#/definitions/AvailabilityZonesContextQuery>,<#/definitions/HostedZoneContextQuery>,<#/definitions/SSMParameterContextQuery>,<#/definitions/VpcContextQuery>,<#/definitions/EndpointServiceAvailabilityZonesContextQuery>,<#/definitions/LoadBalancerContextQuery>,<#/definitions/LoadBalancerListenerContextQuery>,<#/definitions/SecurityGroupContextQuery>,<#/definitions/KeyContextQuery>,<#/definitions/PluginContextQuery>
    at Function.validate (/home/jonatan/Escritorio/Desarrollos/start-stop-mwaa-environment/node_modules/aws-cdk-lib/cloud-assembly-schema/lib/manifest.js:1:3118)
    at Function.saveManifest (/home/jonatan/Escritorio/Desarrollos/start-stop-mwaa-environment/node_modules/aws-cdk-lib/cloud-assembly-schema/lib/manifest.js:3:130)
    at Function.saveAssemblyManifest (/home/jonatan/Escritorio/Desarrollos/start-stop-mwaa-environment/node_modules/aws-cdk-lib/cloud-assembly-schema/lib/manifest.js:1:979)
    at CloudAssemblyBuilder.buildAssembly (/home/jonatan/Escritorio/Desarrollos/start-stop-mwaa-environment/node_modules/aws-cdk-lib/cx-api/lib/cloud-assembly.js:1:5956)
    at Object.synthesize (/home/jonatan/Escritorio/Desarrollos/start-stop-mwaa-environment/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:849)
    at App.synth (/home/jonatan/Escritorio/Desarrollos/start-stop-mwaa-environment/node_modules/aws-cdk-lib/core/lib/stage.js:1:1922)
    at process.<anonymous> (/home/jonatan/Escritorio/Desarrollos/start-stop-mwaa-environment/node_modules/aws-cdk-lib/core/lib/app.js:1:1355)
    at Object.onceWrapper (node:events:629:26)
    at process.emit (node:events:514:28)
    at process.emit (node:domain:489:12)

Subprocess exited with error 1
```

**Comment by crupakheti** [comment]
@jonatan-cepsa Could you please provide a little more details? Which folder are you running the deploy command from, and where is your .env located?

**Comment by crupakheti** [comment]
Closing the issue for now, please reopen it if you still need assistance. Thank you!
